<?php

/** @var \Amasty\DaniilLoban\Block\Timer $block */
?>

<div class="template" data-bind="scope: 'coolTimer'">
    <!-- ko template: getTemplate() -->
    <!-- /ko -->
</div>

<script type="text/x-magento-init">
    {
        "*":{
            "Magento_Ui/js/core/app": {
                "components":{
                    "coolTimer": {
                        "component": "Amasty_DaniilLoban/js/koTimer",
                        "template": "Amasty_DaniilLoban/koTimer"
                    }

                }
            }
        }
    }
</script>